//
//  MTCurrencyItem.swift
//  MarketTrak
//
//  Created by Jonathon Toon on 6/18/16.
//  Copyright © 2016 Jonathon Toon. All rights reserved.
//

import UIKit

class MTCurrencyItem: NSObject {

    let currencies = [
        "USD":[
            "strCode":"USD",
            "eCurrencyCode":1,
            "strSymbol":"$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "GBP":[
            "strCode":"GBP",
            "eCurrencyCode":2,
            "strSymbol":"\u{00a3}",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "EUR":[
            "strCode":"EUR",
            "eCurrencyCode":3,
            "strSymbol":"\u{20ac}",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":false
        ],
        "CHF":[
            "strCode":"CHF",
            "eCurrencyCode":4,
            "strSymbol":"CHF",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "RUB":[
            "strCode":"RUB",
            "eCurrencyCode":5,
            "strSymbol":"\u{0443}\u{0431}",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":true
        ],
        "BRL":[
            "strCode":"BRL",
            "eCurrencyCode":7,
            "strSymbol":"R$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "JPY":[
            "strCode":"JPY",
            "eCurrencyCode":8,
            "strSymbol":"\u{00a5}",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "NOK":[
            "strCode":"NOK",
            "eCurrencyCode":9,
            "strSymbol":"kr",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":false
        ],
        "IDR":[
            "strCode":"IDR",
            "eCurrencyCode":10,
            "strSymbol":"Rp",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "MYR":[
            "strCode":"MYR",
            "eCurrencyCode":11,
            "strSymbol":"RM",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "PHP":[
            "strCode":"PHP",
            "eCurrencyCode":12,
            "strSymbol":"P",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "SGD":[
            "strCode":"SGD",
            "eCurrencyCode":13,
            "strSymbol":"S$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "THB":[
            "strCode":"THB",
            "eCurrencyCode":14,
            "strSymbol":"\u{0e3f}",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "VND":[
            "strCode":"VND",
            "eCurrencyCode":15,
            "strSymbol":"\u{20ab}",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":true
        ],
        "KRW":[
            "strCode":"KRW",
            "eCurrencyCode":16,
            "strSymbol":"\u{20a9}",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "TRY":[
            "strCode":"TRY",
            "eCurrencyCode":17,
            "strSymbol":"TL",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":false
        ],
        "UAH":[
            "strCode":"UAH",
            "eCurrencyCode":18,
            "strSymbol":"\u{20b4}",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":true
        ],
        "MXN":[
            "strCode":"MXN",
            "eCurrencyCode":19,
            "strSymbol":"Mex$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "CAD":[
            "strCode":"CAD",
            "eCurrencyCode":20,
            "strSymbol":"CDN$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "AUD":[
            "strCode":"AUD",
            "eCurrencyCode":21,
            "strSymbol":"A$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "NZD":[
            "strCode":"NZD",
            "eCurrencyCode":22,
            "strSymbol":"NZ$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "PLN":[
            "strCode":"PLN",
            "eCurrencyCode":6,
            "strSymbol":"\u{0142}",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":false
        ],
        "CNY":[
            "strCode":"CNY",
            "eCurrencyCode":23,
            "strSymbol":"\u{00a5}",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "INR":[
            "strCode":"INR",
            "eCurrencyCode":24,
            "strSymbol":"\u{20b9}",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "CLP":[
            "strCode":"CLP",
            "eCurrencyCode":25,
            "strSymbol":"CLP$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "PEN":[
            "strCode":"PEN",
            "eCurrencyCode":26,
            "strSymbol":"S",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "COP":[
            "strCode":"COP",
            "eCurrencyCode":27,
            "strSymbol":"COL$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "ZAR":[
            "strCode":"ZAR",
            "eCurrencyCode":28,
            "strSymbol":"R",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "HKD":[
            "strCode":"HKD",
            "eCurrencyCode":29,
            "strSymbol":"HK$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":false
        ],
        "TWD":[
            "strCode":"TWD",
            "eCurrencyCode":30,
            "strSymbol":"NT$",
            "bSymbolIsPrefix":true,
            "bWholeUnitsOnly":true
        ],
        "SAR":[
            "strCode":"SAR",
            "eCurrencyCode":31,
            "strSymbol":"SR",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":false
        ],
        "AED":[
            "strCode":"AED",
            "eCurrencyCode":32,
            "strSymbol":"AED",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":false
        ],
        "RMB":[
            "strCode":"RMB",
            "eCurrencyCode":9000,
            "strSymbol":"\u{5200}\u{5e01}",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":true
        ],
        "NXP":[
            "strCode":"NXP",
            "eCurrencyCode":9001,
            "strSymbol":"\u{c6d0}",
            "bSymbolIsPrefix":false,
            "bWholeUnitsOnly":true
        ]
    ]

    var currencyCode: String = "USD"
    
    var currencyAmount: NSNumber = 0.0
    
    init(currency: NSNumber) {
        self.currencyAmount = currency
    }

    func formatCurrency() -> String {
        let formatter: NSNumberFormatter = NSNumberFormatter()
            formatter.numberStyle = NSNumberFormatterStyle.CurrencyStyle
            formatter.currencyCode = currencyCode
        return formatter.stringFromNumber(currencyAmount)! + " " + currencyCode
    }
}
